#goal definition
string     operation 	# == 'bcreate' | 'append' | 'predict' | 'delete' | 'list'
                        #   -  'bcreate' creates a new binary wavelet [model] using the corresponding [values] and [timestamps]
                        #   -  'append' appends [values] and [timestamps] to the provided [model], recalculating the model
                        #   -  'predict' returns expected [values] at provided [model] and  [timestamps] 
                        #   -  'delete' drops [model] from server
                        #   -  'list' returns a list of available wavelet models within [message]
string     model  	    # [bcreate, append, predict, delete] unique name to design wavelet model
float32[]  values   	# [bcreate, append] model BINARY data values. future versions will support float ones. 
int32[]    timestamps 	# [bcreate, append, predict] timestamps for values, POSIX seconds

---
#result definition
bool success		    # [all]     operation result
float32[]  values   	# [predict] predicted values
string message 		    # [all]     description of result AND list of wavelet models
---
#feedback
string status           # [all]
